In [1]:
import pandas as pd

In [5]:
df = pd.DataFrame([[1, 2, 3], [ 4, 5, 6], [7, 8, 9]], columns = ["A", "B", "C"])

### Basic Practice

In [9]:
df.head()
df.head(1)

   A  B  C
0  1  2  3

In [10]:
df.tail()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [11]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [12]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [15]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [22]:
df.nunique()
df['A'].nunique()

3

In [25]:
df.shape

(3, 3)

In [27]:
df.describe

<bound method NDFrame.describe of    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9>

In [28]:
df.size

9

### Sample Data

In [29]:
coffee = pd.read_csv("./warmup-data/coffee.csv")

In [31]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [34]:
results = pd.read_parquet("./data/results.parquet")
bios = pd.read_csv("./data/bios.csv")

In [39]:
coffee.loc[[0, 1, 2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [42]:
coffee.loc[0:3, "Day"]

0     Monday
1     Monday
2    Tuesday
3    Tuesday
Name: Day, dtype: object

In [44]:
coffee.iloc[:, [0, 2]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [46]:
coffee.loc[1, "Units Sold"] = 20

In [47]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          20
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35