In [1]:
import pandas as pd

# 5.1 Introduction to pandas Data Structure

## Series

In [2]:
obj = pd.Series([4, 5, 7, 8])
obj

0    4
1    5
2    7
3    8
dtype: int64

In [3]:
obj.array

<PandasArray>
[4, 5, 7, 8]
Length: 4, dtype: int64

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([1, 2, 3, 4], index = ['D', 'A', 'C', 'B'])

In [6]:
obj2

D    1
A    2
C    3
B    4
dtype: int64

In [7]:
obj2.index

Index(['D', 'A', 'C', 'B'], dtype='object')

In [8]:
obj2['B']

4

In [9]:
obj2['B'] = 0
obj2

D    1
A    2
C    3
B    0
dtype: int64

In [10]:
obj2[obj2 > 0]

D    1
A    2
C    3
dtype: int64

In [11]:
obj2*2

D    2
A    4
C    6
B    0
dtype: int64

In [12]:
import numpy as np

In [13]:
np.exp(obj2)

D     2.718282
A     7.389056
C    20.085537
B     1.000000
dtype: float64

In [14]:
"B" in obj2

True

In [15]:
sdata = {
    "Ohio": 35000,
    "Texas": 71000,
    "Oregon": 16000,
    "Utah": 5000
}

obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [17]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)

In [18]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [21]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [23]:
obj4.name = "population"

obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [24]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    5
Jeff     7
Ryan     8
dtype: int64

## DataFrame

In [26]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)

frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [27]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [28]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [29]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [31]:
frame2 = pd.DataFrame(data, columns = ["year", "state", "pop", "debt"])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [32]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [33]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [34]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [35]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [36]:
frame2["debt"] = 10
frame2

   year   state  pop  debt
0  2000    Ohio  1.5    10
1  2001    Ohio  1.7    10
2  2002    Ohio  3.6    10
3  2001  Nevada  2.4    10
4  2002  Nevada  2.9    10
5  2003  Nevada  3.2    10

In [37]:
d = 10
for i in range(6):
    frame2["debt"].loc[i] = d
    d += 2

frame2

C:\Users\Atharva\AppData\Local\Temp\ipykernel_13516\3101432821.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame2["debt"].loc[i] = d

   year   state  pop  debt
0  2000    Ohio  1.5    10
1  2001    Ohio  1.7    12
2  2002    Ohio  3.6    14
3  2001  Nevada  2.4    16
4  2002  Nevada  2.9    18
5  2003  Nevada  3.2    20

In [38]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5    10     True
1  2001    Ohio  1.7    12     True
2  2002    Ohio  3.6    14     True
3  2001  Nevada  2.4    16    False
4  2002  Nevada  2.9    18    False
5  2003  Nevada  3.2    20    False