In [1]:
import pandas as pd

In [9]:
df = pd.DataFrame({
    'age': [18, 19, 20],
    'name': ["Atharva", "Ajay", "Sameer"],
    'work': ["Computers", "Machines", "Electrical"],
})

### Basic Start of Pandas

In [10]:
df.head()

   age     name        work
0   18  Atharva   Computers
1   19     Ajay    Machines
2   20   Sameer  Electrical

In [14]:
df.shape

(3, 3)

In [18]:
df.columns

Index(['age', 'name', 'work'], dtype='object')

In [20]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [22]:
df.dtypes

age      int64
name    object
work    object
dtype: object

In [24]:
df.values

array([[18, 'Atharva', 'Computers'],
       [19, 'Ajay', 'Machines'],
       [20, 'Sameer', 'Electrical']], dtype=object)

In [25]:
df.to_csv("practice_output.csv", index=False)

### Basic ML operations of pandas

In [26]:
df.head()

   age     name        work
0   18  Atharva   Computers
1   19     Ajay    Machines
2   20   Sameer  Electrical